config/routes.rb
Rails.application.routes.draw do

  resources :user_projects
  resources :artifacts
  resources :tenants do 
    resources :projects do 
      get 'users', on: :member
      put 'add_user', on: :member
    end
  end
  
  resources :members
  get 'home/index'

  root :to => "home#index"
    
  # *MUST* come *BEFORE* devise's definitions (below)
  as :user do   
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => { 
    :registrations => "registrations",
    :confirmations => "confirmations",
    :sessions => "milia/sessions", 
    :passwords => "milia/passwords", 
  }
  
  match '/plan/edit' => 'tenants#edit', via: :get, as: :edit_plan
  match '/plan/update' => 'tenants#update', via: [:put, :patch], as: :update_plan


end

app/models/user_project.rb
class UserProject < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/controllers/user_projects_controller.rb
class UserProjectsController < ApplicationController
  before_action :set_user_project, only: [:show, :edit, :update, :destroy]

  # GET /user_projects
  # GET /user_projects.json
  def index
    @user_projects = UserProject.all
  end

  # GET /user_projects/1
  # GET /user_projects/1.json
  def show
  end

  # GET /user_projects/new
  def new
    @user_project = UserProject.new
  end

  # GET /user_projects/1/edit
  def edit
  end

  # POST /user_projects
  # POST /user_projects.json
  def create
    @user_project = UserProject.new(user_project_params)

    respond_to do |format|
      if @user_project.save
        format.html { redirect_to @user_project, notice: 'User project was successfully created.' }
        format.json { render :show, status: :created, location: @user_project }
      else
        format.html { render :new }
        format.json { render json: @user_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_projects/1
  # PATCH/PUT /user_projects/1.json
  def update
    respond_to do |format|
      if @user_project.update(user_project_params)
        format.html { redirect_to @user_project, notice: 'User project was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_project }
      else
        format.html { render :edit }
        format.json { render json: @user_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_projects/1
  # DELETE /user_projects/1.json
  def destroy
    @user_project.destroy
    respond_to do |format|
      format.html { redirect_to users_tenant_project_url(id: @user_project.project_id,tenant_id: @user_project.project.tenant_id),notice: 'User was successfully removed from the project' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_project
      @user_project = UserProject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_project_params
      params.require(:user_project).permit(:project_id, :user_id)
    end
end

app/helpers/user_projects_helper.rb
module UserProjectsHelper
end

app/views/user_projects/_form.html.erb
<%= form_for @user_project, :html => { :class => "form-horizontal user_project" } do |f| %>

  <% if @user_project.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user_project.errors.count, "error") %> prohibited this user_project from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user_project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :project_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :project_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:project_id) %>
  </div>
  <div class="form-group">
    <%= f.label :user_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :user_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:user_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                user_projects_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/user_projects/edit.html.erb
<%- model_class = UserProject -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/user_projects/index.html.erb
<%- model_class = UserProject -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:project_id) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @user_projects.each do |user_project| %>
      <tr>
        <td><%= link_to user_project.id, user_project_path(user_project) %></td>
        <td><%= user_project.project_id %></td>
        <td><%= user_project.user_id %></td>
        <td><%=l user_project.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      user_project_path(user_project), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_project_path(user_project), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_project_path(user_project),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_project_path,
            :class => 'btn btn-primary' %>

app/views/user_projects/new.html.erb
<%- model_class = UserProject -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/user_projects/show.html.erb
<%- model_class = UserProject -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:project_id) %>:</strong></dt>
  <dd><%= @user_project.project_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @user_project.user_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              user_projects_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_project_path(@user_project), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_project_path(@user_project),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>